//
// This file was generated by the JPA Modeler
//
package br.edu.ifpb.ads.praticas.immobilly.shared.beans;

import br.edu.ifpb.ads.praticas.immobilly.shared.beans.outros.CatType;
import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;

@Entity
public class Fornecedor implements Serializable {

    @Column(unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    @Basic
    private String telefone;

    @Column(unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    @Basic
    private String nomeFantasia;

    @Embedded
    private Endereço endereco;

    @Column(unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    @Basic
    @Enumerated(EnumType.STRING)
    private CatType categoria;

    @Column(unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    @Id
    private long cod;

    @Column(unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    @Basic
    private String razaoSocial;

    @Column(unique = false, updatable = true, insertable = true, nullable = true, length = 255, scale = 0, precision = 0)
    @Basic
    private String email;

    public Fornecedor() {

    }

    public String getTelefone() {
        return this.telefone;
    }

    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    public String getNomeFantasia() {
        return this.nomeFantasia;
    }

    public void setNomeFantasia(String nomeFantasia) {
        this.nomeFantasia = nomeFantasia;
    }

    public Endereço getEndereco() {
        return this.endereco;
    }

    public void setEndereco(Endereço endereco) {
        this.endereco = endereco;
    }

    public CatType getCategoria() {
        return this.categoria;
    }

    public void setCategoria(CatType categoria) {
        this.categoria = categoria;
    }

    public long getCod() {
        return this.cod;
    }

    public void setCod(long cod) {
        this.cod = cod;
    }

    public String getRazaoSocial() {
        return this.razaoSocial;
    }

    public void setRazaoSocial(String razaoSocial) {
        this.razaoSocial = razaoSocial;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}
