
/**
 * Author:  Aluísio
 * Created: 24/09/2016
 */
CREATE TABLE COLABORADOR (COD BIGINT NOT NULL, CARGO VARCHAR, CELULAR VARCHAR, DATANASCIMENTO DATE, EMAIL VARCHAR, NOME VARCHAR, SENHA VARCHAR, SEXO VARCHAR, CATEGORIA VARCHAR, RENACH VARCHAR, VALIDADE DATE, BAIRRO VARCHAR, CEP VARCHAR, CIDADE VARCHAR, NUMERO INTEGER, RUA VARCHAR, UF VARCHAR, PRIMARY KEY (COD));
CREATE TABLE VEICULO (COD BIGINT NOT NULL, ANOFABRICACAO DATE, CATEGORIA VARCHAR, CHASSI VARCHAR, COMBUSTIVEL VARCHAR, COR VARCHAR, FABRICANTE VARCHAR, KM INTEGER, MODELO VARCHAR, RENAVAN VARCHAR, STATUS VARCHAR, PRIMARY KEY (COD));
CREATE TABLE LOCACAO (ID BIGINT NOT NULL, HORARIORETORNO TIMESTAMP, HORARIOSAIDA TIMESTAMP, KMRETORNO INTEGER, KMSAIDA INTEGER, COLABORADOR_COD BIGINT, VEICULO_COD BIGINT, PRIMARY KEY (ID));
CREATE TABLE RESERVA (ID BIGINT NOT NULL, HORARIORETORNO TIMESTAMP, HORARIOSAIDA TIMESTAMP, STATUS INTEGER, COLABORADOR_COD BIGINT, VEICULO_COD BIGINT, PRIMARY KEY (ID));
CREATE TABLE FORNECEDOR (COD BIGINT NOT NULL, EMAIL VARCHAR, NOMEFANTASIA VARCHAR, RAZAOSOCIAL VARCHAR, TELEFONE VARCHAR, BAIRRO VARCHAR, CEP VARCHAR, CIDADE VARCHAR, NUMERO INTEGER, RUA VARCHAR, UF VARCHAR, PRIMARY KEY (COD));
CREATE TABLE ABASTECIMENTO (ABASTECIMENTOID BIGINT NOT NULL, HORARIO TIMESTAMP, KM INTEGER, QUANTIDADE INTEGER, VALORABASTECIMENTO NUMERIC(38), VALORPORLITRO NUMERIC(38), FORNECEDOR_COD BIGINT, VEICULO_COD BIGINT, PRIMARY KEY (ABASTECIMENTOID));
ALTER TABLE LOCACAO ADD CONSTRAINT FK_LOCACAO_VEICULO_COD FOREIGN KEY (VEICULO_COD) REFERENCES VEICULO (COD);
ALTER TABLE LOCACAO ADD CONSTRAINT FK_LOCACAO_COLABORADOR_COD FOREIGN KEY (COLABORADOR_COD) REFERENCES COLABORADOR (COD);
ALTER TABLE RESERVA ADD CONSTRAINT FK_RESERVA_COLABORADOR_COD FOREIGN KEY (COLABORADOR_COD) REFERENCES COLABORADOR (COD);
ALTER TABLE RESERVA ADD CONSTRAINT FK_RESERVA_VEICULO_COD FOREIGN KEY (VEICULO_COD) REFERENCES VEICULO (COD);
ALTER TABLE ABASTECIMENTO ADD CONSTRAINT FK_ABASTECIMENTO_FORNECEDOR_COD FOREIGN KEY (FORNECEDOR_COD) REFERENCES FORNECEDOR (COD);
ALTER TABLE ABASTECIMENTO ADD CONSTRAINT FK_ABASTECIMENTO_VEICULO_COD FOREIGN KEY (VEICULO_COD) REFERENCES VEICULO (COD);
